import { createHmac, timingSafeEqual } from "crypto";

/**
 * Helpers for the Sentry integration webhook receiver (`./route.ts`) — kept
 * in a SIBLING module per this codebase's convention that a `route.ts` file
 * exports only its HTTP method handlers, nothing else (mirrors
 * `published-helpers.ts`, `digest-helpers.ts`,
 * `workspaces/[workspaceId]/connectors/secret/verify.ts`).
 *
 * DOC-VERIFICATION (BINDING — raw `curl`, not a WebFetch summary; W3-T5,
 * `.superpowers/sdd/task-W3T5-report.md` carries the full quoted trail):
 * fresh fetches this task of `docs.sentry.io/integrations/
 * integration-platform/webhooks.md` (the integration-platform Webhooks
 * page) and its `webhooks/installation.md` child page.
 *
 * SIGNATURE — CONFIRMED, quoted. The header is `Sentry-Hook-Signature`
 * (read case-insensitively as `sentry-hook-signature` — the doc's own
 * verification snippet reads it that way:
 * `request.headers["sentry-hook-signature"]`), described as "a
 * cryptographic hash generated by your *Client Secret*" — the SAME
 * `SENTRY_OAUTH_CLIENT_SECRET` this codebase already stores for the OAuth
 * token exchange (W3-T3, `lib/oauth/sentry.ts`): a Sentry Public
 * Integration has exactly ONE Client Secret, used for both purposes. The
 * doc's own worked (Express-style) snippet:
 *
 *   "const hmac = crypto.createHmac("sha256", secret);
 *    hmac.update(JSON.stringify(request.body), "utf8");
 *    const digest = hmac.digest("hex");
 *    return digest === request.headers["sentry-hook-signature"];"
 *
 * — HMAC-SHA256, hex digest, keyed by the client secret. DISCLOSED
 * DEVIATION from the snippet's own `JSON.stringify(request.body)`: that
 * re-serializes an ALREADY-PARSED body, which is only byte-identical to
 * what Sentry actually signed if the parse/stringify round-trip happens to
 * be lossless — not a safe assumption in general (whitespace, key order,
 * and unicode escaping can all differ between two independent JSON
 * serializers). This receiver instead verifies over the UNTOUCHED raw
 * request bytes, read BEFORE any `JSON.parse` — the more strictly correct
 * source of truth (it is the exact byte sequence Sentry's own signer
 * hashed) and the same discipline every other webhook receiver in this
 * codebase already follows (`connectors/github/webhook/route.ts`'s
 * `request.text()` before `JSON.parse`; `billing/stripe/webhook/route.ts`'s
 * identical ordering, there enforced by the Stripe SDK itself).
 *
 * RESOURCE/ACTION — CONFIRMED, quoted. `Sentry-Hook-Resource` "lets you
 * know which resource ... triggered an action" — `installation` is one of
 * eight listed values (alongside `event_alert`/`issue`/`metric_alert`/
 * `error`/`comment`/`seer`/`preprod_artifact`). `webhooks/installation.md`'s
 * own "Sentry-Hook-Resource Header" section pins the exact value for this
 * resource: "'Sentry-Hook-Resource': 'installation'". That page's own
 * `action` attribute (a top-level JSON field, not a header): "type:
 * string, description: `created` or `deleted`" — confirming those are the
 * ONLY two action values for the installation resource. Checking BOTH the
 * resource header AND the action field is required, not merely defensive:
 * the general webhooks page's own words — "the action ... could be
 * `created`" FOR THE `issue` RESOURCE, as its own example — confirm
 * `action` values are resource-scoped vocabulary, so an `action: "deleted"`
 * on a DIFFERENT resource (e.g. a deleted `comment`) is a wholly unrelated
 * event that must never be read as an installation uninstall.
 *
 * INSTALLATION UUID — CONFIRMED, quoted, present TWICE in the SAME payload
 * (redundant, not conflicting). The general webhooks page: "installation:
 * An object with the `uuid` of the installation so that you can map the
 * webhook request to the appropriate installation" — documented as a
 * "common element" of ALL webhook requests, not installation-resource
 * specific. The installation resource's own worked JSON example shows this
 * exact top-level shape — `"installation": { "uuid":
 * "a8e5d37a-696c-4c54-adb5-b3f28d64c7de" }` — alongside a SECOND, richer
 * copy of the SAME value nested at `data.installation.uuid` (inside the
 * resource-specific `data.installation` object, which additionally carries
 * `status`/`organization`/`app`/`code`). This module reads the TOP-LEVEL
 * `installation.uuid` — the resource-agnostic location — so the same read
 * path keeps working if a future task ever needs a different resource's
 * payload.
 *
 * RESPONSE — the docs state only a latency requirement ("Webhooks should
 * respond within 1 second. Otherwise, the response is considered a
 * timeout.") — NOT an explicit retry-on-non-2xx policy (unlike, say,
 * GitHub's documented redelivery behavior). `route.ts`'s "200 for every
 * verified event" choice is therefore this codebase's OWN defensive
 * default (matching `billing/stripe/webhook/route.ts`'s identical
 * "recognized-but-ignored -> 200" convention), disclosed as a design
 * choice rather than presented as a vendor-quoted requirement.
 */

export const SENTRY_WEBHOOK_SIGNATURE_HEADER = "sentry-hook-signature";
export const SENTRY_WEBHOOK_RESOURCE_HEADER = "sentry-hook-resource";

export const SENTRY_INSTALLATION_RESOURCE = "installation";
export const SENTRY_INSTALLATION_ACTION_DELETED = "deleted";
export const SENTRY_INSTALLATION_ACTION_CREATED = "created";

/**
 * Timing-safe HMAC-SHA256 verification over the RAW request body (see this
 * module's own doc-comment, "SIGNATURE"). `secret` is
 * `SENTRY_OAUTH_CLIENT_SECRET`, read and env-gated by the route BEFORE this
 * is ever called — this function stays a pure function of its inputs,
 * mirroring every sibling helper module in this codebase.
 *
 * Never throws: a missing header is rejected outright; `Buffer.from` on
 * BOTH sides encodes the two hex STRINGS as UTF-8 byte buffers (comparing
 * the text, not hex-decoding first) — the SAME idiom
 * `connectors/github/webhook/route.ts`'s `verifySignature` already
 * established in this codebase (deliberately mirrored rather than
 * reinvented), which also sidesteps `Buffer.from(str, "hex")`'s own
 * documented leniency (it silently stops decoding at the first invalid
 * pair rather than throwing — a footgun this UTF-8-text comparison never
 * has to reason about). A length mismatch — the cheapest, non-secret-
 * dependent signal a malformed/truncated/wrong-length header can produce —
 * is checked BEFORE calling `timingSafeEqual` (which otherwise throws a
 * `RangeError` on mismatched-length buffers), so any malformed header is
 * treated as an ordinary invalid signature, never a 500.
 */
export function verifySentryWebhookSignature(
  raw: string,
  signatureHeader: string | null,
  secret: string
): boolean {
  if (!signatureHeader) return false;
  const expected = createHmac("sha256", secret).update(raw, "utf8").digest("hex");
  const expectedBuf = Buffer.from(expected, "utf8");
  const actualBuf = Buffer.from(signatureHeader, "utf8");
  if (expectedBuf.length !== actualBuf.length) return false;
  return timingSafeEqual(actualBuf, expectedBuf);
}

/** The subset of a verified Sentry webhook payload this receiver reads —
 * loosely typed and defensively parsed (never trusts the shape), mirroring
 * every other webhook receiver in this codebase (`github/webhook/route.ts`'s
 * `Record<string, unknown>` payload reads). */
export interface SentryWebhookPayload {
  action: string | null;
  installationId: string | null;
}

/**
 * Defensively parses a verified Sentry webhook's JSON body. Returns `null`
 * when the body doesn't even parse as JSON, OR parses to something that
 * isn't a genuine JSON OBJECT (Sentry's own documented payload shape is
 * always `{action, installation, data, actor}` — never a bare array,
 * string, number, or `null`; `Array.isArray` is checked explicitly because
 * `typeof [] === "object"` in JS would otherwise silently let an array
 * through this guard) — the route's own caller decides what response that
 * gets (see `route.ts`'s own doc-comment for the disclosed 400-vs-200
 * judgment call). A genuine object that's merely missing/off-shape fields
 * (e.g. `installation` absent, or not itself an object) degrades
 * field-by-field to `null` VALUES on an otherwise-real result, rather than
 * this function returning `null` outright — this function is never the
 * reason a verified, signed request gets a 5xx.
 */
export function parseSentryWebhookPayload(raw: string): SentryWebhookPayload | null {
  let body: unknown;
  try {
    body = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!body || typeof body !== "object" || Array.isArray(body)) return null;
  const b = body as Record<string, unknown>;

  const action = typeof b["action"] === "string" ? (b["action"] as string) : null;

  const installation = b["installation"];
  const installationId =
    installation &&
    typeof installation === "object" &&
    typeof (installation as Record<string, unknown>)["uuid"] === "string"
      ? ((installation as Record<string, unknown>)["uuid"] as string)
      : null;

  return { action, installationId };
}

/**
 * Log-line hygiene for attacker-influenced strings (review W3-T5, LOW-1):
 * the resource header and `payload.action` are interpolated into one
 * `console.log` line in the route. Reachable only by a caller who already
 * holds the HMAC secret, but a signed caller still must not be able to
 * forge multi-line log records or smuggle control characters into log
 * pipelines. Strips C0/C1 controls (incl. newlines) and caps length; a
 * capped value is marked with a trailing `…` so a truncated record is
 * visibly truncated.
 */
export function sanitizeForLog(value: string | null, maxLength = 64): string {
  if (value == null) return "unknown";
  // eslint-disable-next-line no-control-regex
  const stripped = value.replace(/[\u0000-\u001f\u007f-\u009f]/g, "");
  return stripped.length > maxLength ? `${stripped.slice(0, maxLength)}…` : stripped;
}
