export { client } from "./client";
export {
  CREATE_RUN_EVENTS_TABLE,
  CREATE_FAILURE_EVENTS_TABLE,
  CREATE_CONTEXT_PACKS_TABLE,
  CREATE_CONTEXT_EVENTS_TABLE,
  CREATE_INDEX_SNAPSHOTS_TABLE,
  CREATE_COST_EVENTS_TABLE,
  ALTER_RUN_EVENTS_ADD_SESSION_ID,
  ALTER_RUN_EVENTS_ADD_SEQ,
  ALTER_FAILURE_EVENTS_ADD_NORMALIZED_ERROR,
  ALTER_FAILURE_EVENTS_ADD_FINGERPRINT,
  ALTER_RUN_EVENTS_ADD_FILES_READ_COUNT,
  ALTER_RUN_EVENTS_ADD_FULL_FILE_READ,
  ALTER_RUN_EVENTS_ADD_TOOL_LOOP_COUNT,
  ALTER_RUN_EVENTS_ADD_EDIT_WITHOUT_CONTEXT,
  ALTER_RUN_EVENTS_ADD_VERIFICATION_SKIP,
  ALTER_CONTEXT_PACKS_ADD_PRECISION_AT_BUDGET,
  ALTER_CONTEXT_PACKS_ADD_CITATION_COVERAGE,
  ALTER_CONTEXT_PACKS_ADD_STALE_COUNT,
  ALTER_CONTEXT_PACKS_ADD_DENIED_COUNT,
  ALTER_CONTEXT_PACKS_ADD_SOURCE_HASH_LIST,
  ALTER_COST_EVENTS_ADD_PHASE,
  ALTER_COST_EVENTS_ADD_INPUT_TOKENS,
  ALTER_COST_EVENTS_ADD_OUTPUT_TOKENS,
  ALTER_COST_EVENTS_ADD_CACHE_TOKENS,
  CREATE_AFK_RUN_EVENTS_TABLE,
} from "./schema";
export type {
  TelemetryEventRecord,
  FailureEventRecord,
  ContextPackRecord,
  ContextEventRecord,
  IndexSnapshotRecord,
  CostEventRecord,
  AfkRunEventRecord,
} from "./schema";
export {
  getRunEvents,
  getRunEventSummaries,
  getFailuresForRun,
  listWorkspaceFailures,
  listFailureClusters,
  getFailureById,
  aggregateWorkspaceCosts,
  getLatestIndexSnapshotsForWorkspace,
  insertAfkRunEvents,
  insertIndexSnapshots,
  deriveSnapshotEventId,
  insertFailureEvents,
  deriveFailureEventId,
  insertCostEvents,
  deriveCostEventId,
  getRunEventsByRunId,
  insertContextPacks,
  deriveContextPackId,
  insertContextEvents,
  getWorkspaceTelemetryCounts,
  getRunCosts,
  getRunTelemetryHealth,
  TELEMETRY_HEALTH_SIGNALS,
  listCostAnomalies,
  getAgentModelCosts,
  countDistinctSourceHashLists,
  insertFlightRecorderEvents,
  getAfkRunEvents,
  getRunnerCostStats,
  getRunnerContextEfficiency,
  getWorkspaceAuditEvents,
  APPROVAL_AUDIT_EVENT_TYPES,
} from "./queries";
export type {
  RunEventSummary,
  ListWorkspaceFailuresOptions,
  FailureClusterRecord,
  CostGroupBy,
  CostAggregateRow,
  AggregateCostsOptions,
  AfkRunEventInput,
  IndexSnapshotInput,
  FailureEventInput,
  CostEventInput,
  ContextPackInput,
  ContextEventInput,
  WorkspaceTelemetryCounts,
  RunCostRow,
  TelemetryHealthSignal,
  TelemetryHealthSignalRow,
  CostAnomalyRow,
  ListCostAnomaliesOptions,
  AgentModelCostRow,
  HashChurnResult,
  AfkFlightEventInput,
  InsertFlightRecorderResult,
  RunnerCostStatsRow,
  RunnerContextEfficiencyRow,
  AuditEventRow,
} from "./queries";
export { getContextPacksForRun, getContextPackItems, getWorkspaceContextPacks, listWorkspaceContextPacks, getTokensSavedByRun } from "./context-queries";
export { computeQualityMetrics, getQualityMetrics } from "./quality-metrics";
export type { QualityMetricsResult, QualityMetricsOpts, QualityPackRow } from "./quality-metrics";
export {
  computeCacheReadCreationRatio,
  computeCostPerIssueToGreen,
  getCacheReadCreationRatio,
  getRunCostTotals,
  getAgentCostBreakdown,
} from "./cost-meter";
export type {
  CacheTokenRow,
  CacheReadCreationRatio,
  RunCost,
  IssueGroup,
  IssueCost,
  CostPerIssueToGreen,
  CostMeterTimeOptions,
  AgentCostBreakdownRow,
} from "./cost-meter";
export {
  AgentBehaviorLinter,
  DEFAULT_BEHAVIOR_THRESHOLDS,
} from "./linter";
export type {
  BehaviorRule,
  BehaviorThresholds,
  LintFinding,
  LintSeverity,
} from "./linter";
