export { client } from "./client";
export {
  CREATE_RUN_EVENTS_TABLE,
  CREATE_FAILURE_EVENTS_TABLE,
  CREATE_CONTEXT_PACKS_TABLE,
  CREATE_CONTEXT_EVENTS_TABLE,
  CREATE_INDEX_SNAPSHOTS_TABLE,
  CREATE_COST_EVENTS_TABLE,
  ALTER_RUN_EVENTS_ADD_SESSION_ID,
  ALTER_RUN_EVENTS_ADD_SEQ,
  ALTER_CONTEXT_PACKS_ADD_PRECISION_AT_BUDGET,
  ALTER_CONTEXT_PACKS_ADD_CITATION_COVERAGE,
  ALTER_CONTEXT_PACKS_ADD_STALE_COUNT,
  ALTER_CONTEXT_PACKS_ADD_DENIED_COUNT,
  ALTER_CONTEXT_PACKS_ADD_SOURCE_HASH_LIST,
  ALTER_COST_EVENTS_ADD_PHASE,
  ALTER_COST_EVENTS_ADD_INPUT_TOKENS,
  ALTER_COST_EVENTS_ADD_OUTPUT_TOKENS,
  ALTER_COST_EVENTS_ADD_CACHE_TOKENS,
} from "./schema";
export type {
  TelemetryEventRecord,
  FailureEventRecord,
  ContextPackRecord,
  ContextEventRecord,
  IndexSnapshotRecord,
  CostEventRecord,
} from "./schema";
export {
  getRunEvents,
  getRunEventSummaries,
  getFailuresForRun,
  listWorkspaceFailures,
  getFailureById,
  aggregateWorkspaceCosts,
  getLatestIndexSnapshotsForWorkspace,
  insertAfkRunEvents,
  insertIndexSnapshots,
  deriveSnapshotEventId,
  insertFailureEvents,
  deriveFailureEventId,
  insertCostEvents,
  deriveCostEventId,
  getRunEventsByRunId,
  insertContextPacks,
  deriveContextPackId,
  insertContextEvents,
  getWorkspaceTelemetryCounts,
  getRunCosts,
  getAgentModelCosts,
  countDistinctSourceHashLists,
} from "./queries";
export type {
  RunEventSummary,
  ListWorkspaceFailuresOptions,
  CostGroupBy,
  CostAggregateRow,
  AggregateCostsOptions,
  AfkRunEventInput,
  IndexSnapshotInput,
  FailureEventInput,
  CostEventInput,
  ContextPackInput,
  ContextEventInput,
  WorkspaceTelemetryCounts,
  RunCostRow,
  AgentModelCostRow,
  HashChurnResult,
} from "./queries";
export { getContextPacksForRun, getContextPackItems, getWorkspaceContextPacks, listWorkspaceContextPacks, getTokensSavedByRun } from "./context-queries";
export { computeQualityMetrics, getQualityMetrics } from "./quality-metrics";
export type { QualityMetricsResult, QualityMetricsOpts, QualityPackRow } from "./quality-metrics";
