/**
 * Compatibility surface for Console callers. Rendering belongs to the DB
 * package because DB custody, not a transport adapter, derives comment bodies.
 */
export {
  GITHUB_CORRECTION_ACTIVATION_BINDING_KIND,
  GITHUB_CORRECTION_ACTIVATION_BINDING_VERSION,
  GITHUB_CORRECTION_ACTIVATION_BUNDLE_KIND,
  GITHUB_CORRECTION_ACTIVATION_BUNDLE_VERSION,
  GITHUB_CORRECTION_DISPATCH_BINDING_KIND,
  GITHUB_CORRECTION_DISPATCH_BINDING_VERSION,
  MAX_GITHUB_CORRECTION_ACTIVATION_BYTES,
  MAX_GITHUB_CORRECTION_FINDING_BYTES,
  githubCorrectionPacketPayloadSha256,
  isExactGitHubCorrectionFindingComment,
  parseGitHubCorrectionFindingComment,
  renderGitHubCorrectionActivation,
  renderGitHubCorrectionFinding,
  validateGitHubCorrectionActivationBinding,
  validateGitHubCorrectionDispatchBinding,
  validateGitHubCorrectionPacketPayload,
  type GitHubCorrectionActivationBinding,
  type GitHubCorrectionActivationRendering,
  type GitHubCorrectionDispatchBinding,
  type GitHubCorrectionPacketPayload,
  type GitHubCorrectionRecipient,
  type GitHubCorrectionReproduction,
  type GitHubCorrectionRouteAdapter,
  type InvalidGitHubCorrectionActivationRendering,
  type OversizeGitHubCorrectionActivationRendering,
  type RenderedGitHubCorrectionActivation,
  type RenderedGitHubCorrectionFinding,
  type SafeDataCorrectionRequestDescriptor,
  type SafeUiCorrectionReproductionStep,
} from "@agentrail/db-postgres";
