"""Pure dependency-observation contracts."""

from agentrail.dependencies.execution import (
    ApprovedPnpmUpgrade,
    CommandEvidence,
    DependencyExecutionResult,
    ExecutionReason,
    ExecutionStatus,
    Toolchain,
    execute_approved_dependency_upgrade,
    execute_approved_pnpm_upgrade,
    write_dependency_execution_evidence,
)

from agentrail.dependencies.evidence import (
    CandidateIdentity,
    DependencyChange,
    DependencyDecisionStatus,
    DependencyEvidence,
    DependencyEvidenceDecision,
    EvidenceResolution,
    EvidenceSource,
    EvidenceState,
    EvidenceWaiver,
    LockResolution,
    PeerConflict,
    ReleaseEvidence,
    SecurityAdvisory,
    SecurityEvidence,
    UsageEvidence,
    UsageFinding,
    collect_dependency_evidence,
    dependency_gate_input,
    evaluate_dependency_evidence,
    resolve_pnpm_lock_transition,
    scan_usage_evidence,
    security_evidence_from_advisory_payload,
    write_dependency_evidence,
)

from agentrail.dependencies.pnpm import (
    CandidatesResult,
    DependencyCandidate,
    DependencySnapshot,
    InsufficientEvidenceResult,
    ObservationResult,
    ObservationStatus,
    RegistryAdapter,
    RegistryPackage,
    TargetVersionAdapter,
    UnchangedResult,
    UnsupportedResult,
    observe_pnpm_dependencies,
)

from agentrail.dependencies.observation import observe_dependencies, observe_dependency_candidates
from agentrail.dependencies.manager import (
    CommandPlan,
    DetectionResult,
    DetectionStatus,
    Ecosystem,
    ManagerId,
    RepositorySnapshot,
    SupportedDetection,
    UnsupportedDetection,
    detect_dependency_manager,
)
from agentrail.dependencies.publication import (
    DependencyPublicationDecision,
    build_dependency_pr_body,
    evaluate_dependency_publication,
    is_dependency_publication,
)

__all__ = [
    "ApprovedPnpmUpgrade",
    "CandidateIdentity",
    "CommandEvidence",
    "DependencyChange",
    "DependencyDecisionStatus",
    "DependencyEvidence",
    "DependencyEvidenceDecision",
    "DependencyExecutionResult",
    "DependencyPublicationDecision",
    "CandidatesResult",
    "DependencyCandidate",
    "DependencySnapshot",
    "EvidenceResolution",
    "EvidenceSource",
    "EvidenceState",
    "EvidenceWaiver",
    "ExecutionReason",
    "ExecutionStatus",
    "InsufficientEvidenceResult",
    "LockResolution",
    "ObservationResult",
    "ObservationStatus",
    "PeerConflict",
    "ReleaseEvidence",
    "RegistryAdapter",
    "RegistryPackage",
    "SecurityAdvisory",
    "SecurityEvidence",
    "TargetVersionAdapter",
    "Toolchain",
    "CommandPlan",
    "DetectionResult",
    "DetectionStatus",
    "Ecosystem",
    "ManagerId",
    "RepositorySnapshot",
    "SupportedDetection",
    "UnsupportedDetection",
    "UnchangedResult",
    "UnsupportedResult",
    "UsageEvidence",
    "UsageFinding",
    "collect_dependency_evidence",
    "dependency_gate_input",
    "evaluate_dependency_evidence",
    "execute_approved_dependency_upgrade",
    "execute_approved_pnpm_upgrade",
    "write_dependency_execution_evidence",
    "observe_pnpm_dependencies",
    "resolve_pnpm_lock_transition",
    "scan_usage_evidence",
    "security_evidence_from_advisory_payload",
    "write_dependency_evidence",
    "build_dependency_pr_body",
    "evaluate_dependency_publication",
    "is_dependency_publication",
    "observe_dependencies",
    "observe_dependency_candidates",
    "detect_dependency_manager",
]
